=== frankndrssn/projects/adventure/lib/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title" : "Adventure Schema for CSE 505 2023 Fall",
    "type" : "object",
    "properties": {
        "rooms" : {
            "type" : "array",
            "items" : { "$ref" : "#/$defs/room" }
        },
        "items" : {
            "type" : "array",
            "items" : { "$ref" : "#/$defs/item" }
        },
        "start" : { "type" : "number" },
        "starting_inventory" : { "type" : "array", "items" : { "type" : "number" }},
        "item_locs" : {
            "type" : "array",
            "items" : {
                "type" : "object",
                "properties" : {
                    "item_id" : { "type" : "number" },
                    "room_id" : { "type" : "number" }
                }
            }
        },
        "winning_message" : {"type" : "string"}
    },
    "$defs" : {
        "roomdesc" : {
            "type" : "object", 
            "properties" : {
                "itemids" : {"type" : "array", "items" : {"type" : "number"}},
                "desc" : {"type" : "string"}
            }
        },
        "exit" : {
            "type" : "object",
            "properties" : {
                "direction" : {"type" : "string"},
                "room" : {"type" : "number"},
                "to_unlock" : {"type" : "array", "items" : {"type" : "number"}}
            }
        },
        "room" : {
            "type" : "object",
            "properties" : {
                "id" : { "type" : "number" },
                "descs" : {
                    "type" : "array",
                    "items" : {
                        "$ref" : "#/$defs/roomdesc"
                    }
                },
                "points" : {"type" : "number"},
                "exits" : {"type" : "array", "items" : {"$ref" : "#/$defs/exit"}},
                "to_drop" : {"type" : "array", "items" : {"type" : "number"}}
            }
        },
        "item" : {
            "type" : "object",
            "properties" : {
                "name" : { "type" : "string" },
                "id" : { "type" : "number" },
                "desc" : { "type" : "string" },
                "points" : { "type" : "number" }
            }
        }
    }
}

=== frankndrssn/projects/adventure/example_games/tcs.json
{
    "rooms" : [
        {
            "id" : 0,
            "descs" : [{"itemids" : [], "desc" : "center"}],
            "points" : 1,
            "exits" : [
                {"direction" : "left", "room" : 2, "to_unlock" : [0,1]},
                {"direction" : "right", "room" : 4, "to_unlock" : []}
            ],
            "to_drop" : [0,1,2]
        },
        {
            "id" : 1,
            "descs" : [{"itemids" : [], "desc" : "north"}],
            "points" : 1,
            "exits" : [
                {"direction" : "next room", "room" : 0, "to_unlock" : []}
            ],
            "to_drop" : []
        },
        {
            "id" : 2,
            "descs" : [
                {"itemids" : [0,1,2], "desc" : "west"},
                {"itemids" : [], "desc" : "ha you're stuck"}
            ],
            "points" : 1,
            "exits" : [{"direction" : "next room", "room" : 3, "to_unlock" : [0,1,2]}],
            "to_drop" : []
        },
        {
            "id" : 3,
            "descs" : [{"itemids" : [], "desc" : "south"}],
            "points" : 1,
            "exits" : [{"direction" : "next room", "room" : 0, "to_unlock" : []}],
            "to_drop" : []
        },
        {
            "id" : 4,
            "descs" : [{"itemids" : [], "desc" : "east"}],
            "points" : 1,
            "exits" : [{"direction" : "next room", "room" : 1, "to_unlock" : []}],
            "to_drop" : []
        }
    ],
    "items" : [
        {
            "name" : "item A",
            "id" : 0,
            "desc" : "an item",
            "points" : 1
        },
        {
            "name" : "item B",
            "id" : 1,
            "desc" : "another item",
            "points" : 1
        },
        {
            "name" : "item C",
            "id" : 2,
            "desc" : "yet another item",
            "points" : 1
        }
    ],
    "start" : 0,
    "starting_inventory" : [0],
    "item_locs" : [
        {"item_id" : 1, "room_id" : 1},
        {"item_id" : 2, "room_id" : 2}
    ],
    "winning_message" : "win msg." 
}

=== frankndrssn/projects/adventure/example_games/one_room.json
{
    "rooms" : [
        {
            "id" : 0,
            "descs" : [{"itemids" : [], "desc" : "The only room in this adventure."}],
            "points" : 0,
            "exits" : [],
            "to_drop" : []
        }
    ],
    "items" : [],
    "start" : 0,
    "starting_inventory" : [],
    "item_locs" : [],
    "winning_message" : "You won!" 
}

=== frankndrssn/projects/adventure/example_games/small_circle.json
{
    "rooms" : [
        {
            "id" : 0,
            "descs" : [
                {
                    "itemids" : [0, 1],
                    "desc" : "You're back in the room you started in. The gems in your hands start to glow and vibrate. It's as if they want to be placed in the slots on the altar in front of you."
                },
                {
                    "itemids" : [],
                    "desc" : "You find yourself in a small room. There is an altar in the middle with two slots, one square and one circle. A closed door reads \"exit\". Two open doors lead to two rooms, each seemingly empty except for a shine in the middle of the floor."
                }
            ],
            "points": 0,
            "exits" : [
                {"direction" : "onward", "room": 1, "to_unlock" : []},
                {"direction" : "back", "room" : 2, "to_unlock" : []}
            ],
            "to_drop" : [0,1]
        },
        {
            "id" : 1,
            "descs" : [
                {
                    "itemids" : [0,1],
                    "desc": "This is where you found the circular gem. There are two doors: one to the room with an altar, and another to the room where you found the square gem."
                },
                {
                    "itemids" : [0],
                    "desc" : "This is where you found the circular gem. There are two doors: one to the room with an altar, and another to a room with a square gem sitting on the floor."
                },
                {
                    "itemids" : [1],
                    "desc" : "In front of you lays a small circular gem. There are two doors: one to the room with an altar, and another to a room with a square gem sitting on the floor."
                },
                {
                    "itemids" : [],
                    "desc" : "In front of you lays a small circular gem. There are two doors: one to the room with an altar, and another to a room with a square gem sitting on the floor."    
                }
            ],
            "points" : 0,
            "exits" : [
                {"direction": "back", "room" : 0, "to_unlock" : []},
                {"direction": "onward", "room": 2, "to_unlock" : []}
            ],
            "to_drop" : []
        },
        {
            "id" : 2,
            "descs" : [
                {
                    "itemids" : [0,1],
                    "desc": "This is where you found the square gem. There are two doors: one to the room with an altar, and another to the room where you found the circular gem."
                },
                {
                    "itemids" : [1],
                    "desc" : "This is where you found the square gem. There are two doors: one to the room with an altar, and another to a room with a circular gem sitting on the floor."
                },
                {
                    "itemids" : [0],
                    "desc" : "In front of you lays a small square gem. There are two doors: one to the room with an altar, and another to a room where you found the circular gem."
                },
                {
                    "itemids" : [],
                    "desc" : "In front of you lays a small square gem. There are two doors: one to the room with an altar, and another to a room with a circular gem sitting on the floor."    
                }
            ],
            "points" : 0,
            "exits" : [
                {"direction" : "altar", "room": 0, "to_unlock" : []}, 
                {"direction" : "back", "room" : 1, "to_unlock" : []}
            ],
            "to_drop" : []
        }
    ],
    "items" :[
        {
            "name" : "Circular Gem",
            "id" : 0,
            "desc" : "A small circular gem. It looks like it would fit into the altar in the first room.",
            "points" : 50
        },
        {
            "name" : "Square Gem",
            "id" : 1,
            "desc" : "A small square gem. It looks like it would fit into the altar in the first room.",
            "points" : 50
        }
    ],
    "start" : 0,
    "starting_inventory" : [],
    "item_locs" : [
        {"item_id" : 0, "room_id" : 1},
        {"item_id" : 1, "room_id" : 2}
    ],
   "winning_message" : "As you place the second gem in the altar, the room rumbles as the closed door opens. You step outside and breathe in the fresh air. You still don't know how you got there, but you managed to escape."
}

=== frankndrssn/projects/adventure/example_games/two_rooms.json
{
    "rooms" : [
        {
            "id" : 0,
            "descs" : [
                {
                    "itemids" : [],
                    "desc" : "The first room in this adventure."
                }
            ],
            "points" : 0,
            "exits" : [
                {
                    "direction" : "other",
                    "room" : 1,
                    "to_unlock" : []
                }
            ],
            "to_drop" : []
        },
        {
            "id" : 1,
            "descs" : [
                {
                    "itemids" : [],
                    "desc" : "The second room in this adventure."
                }
            ],
            "points" : 1,
            "exits" : [
                {
                    "direction" : "first",
                    "room" : 0,
                    "to_unlock" : []
                }
            ],
            "to_drop" : []
        }
    ],
    "items" : [],
    "start" : 0,
    "starting_inventory" : [],
    "item_locs" : [],
    "winning_message" : "You win the two-room adventure! Thanks for playing."
}
